name: Bench database

on:
  push:
    branches: [bench-db]
  workflow_dispatch:

jobs:
  bench:
    name: run ${{ matrix.rep }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        rep: [1, 2, 3]
    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: pre-installed
          tools: none
          coverage: none

      - name: Init env
        run: |
          cat > .env <<EOL
          APP_KEY=base64:vHI+YHgkyCDad31iPEErGSNEOWO21wNzV+zyENKQv04=
          APP_URL=http://127.0.0.1:8000
          APP_ENV=testing
          APP_DEBUG=true
          DB_DRIVER=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=librenms_phpunit_78hunjuybybh
          DB_USERNAME=librenms
          DB_PASSWORD=librenms
          DB_TEST_DRIVER=mysql
          DB_TEST_HOST=127.0.0.1
          DB_TEST_PORT=3306
          DB_TEST_DATABASE=librenms_phpunit_78hunjuybybh
          DB_TEST_USERNAME=librenms
          DB_TEST_PASSWORD=librenms
          EOL
          cp tests/testing_config.yaml database/seeders/config/
          sqlite3 database/testing.sqlite ""

      - uses: ./.github/actions/composer-install

      - name: Bench
        run: .github/bench/db2.sh
