name: test

on:
  push:
    branches:
      - "master"
      - "tests/sharded-os"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      test-shard-matrix: ${{ steps.shards.outputs.test-shard-matrix }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            includes/definitions/*.yaml

      - name: Calculate `test-shard-matrix` output
        id: shards
        run: |
          set -x
          declare -r SPLITS=8

          readarray -t INPUT_FILES < <(find includes/definitions/ -maxdepth 1 -name "*.yaml" -printf "%f\n")
          declare -i -r INPUT_FILES_TOTAL=${#INPUT_FILES[@]}

          declare -A FILE_LIST
          for FILE in "${INPUT_FILES[@]}"
          do
            KEY=${FILE:0:2}
            FILE_LIST[$KEY]=$(( ${FILE_LIST[$KEY]:-0} + 1 ))
          done

          declare -r PER_SPLIT=$(( INPUT_FILES_TOTAL / SPLITS ))

          readarray -t FILE_LIST_KEYS < <(printf '%s\n' "${!FILE_LIST[@]}" | sort)

          declare -A SPLIT_GROUPS
          declare -i CURRENT_GROUP=1
          for KEY in "${FILE_LIST_KEYS[@]}"
          do
            (( COUNTER += ${FILE_LIST[$KEY]} ))
            SPLIT_GROUPS[$CURRENT_GROUP]+="${KEY},"
            if [ $COUNTER -ge $PER_SPLIT ]
            then
              COUNTER=0
              (( CURRENT_GROUP++ ))

            fi
          done

          printf "test-shard-matrix=[" >> "$GITHUB_OUTPUT"

          for ((i=1;i<=${#SPLIT_GROUPS[@]};i++)); do
            printf "{\"name\":\"OS 8.3 (%i/%i)\", \"php-version\":\"8.3\", \"skip-web-check\":\"1\", \"database\":\"mariadb:10.5\", \"shard\":\"%s\"}, " $i ${#SPLIT_GROUPS[@]} "${SPLIT_GROUPS[$i]::-1}" >> "$GITHUB_OUTPUT"
          done

          for ((i=1;i<=${#SPLIT_GROUPS[@]};i++)); do
            printf "{\"name\":\"OS 8.2 (%i/%i)\", \"php-version\":\"8.2\", \"skip-web-check\":\"1\", \"database\":\"mysql:8.0\", \"shard\":\"%s\"}, " $i ${#SPLIT_GROUPS[@]} "${SPLIT_GROUPS[$i]::-1}" >> "$GITHUB_OUTPUT"
          done

          printf "]" >> "$GITHUB_OUTPUT"

  test:
    needs: [setup]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.test-shard-matrix) }}

    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: librenms_phpunit_78hunjuybybh
          MYSQL_USER: librenms
          MYSQL_PASSWORD: librenms
        ports:
          - 3306
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set $PATH
        run: |
          echo "/home/runner/.local/bin/" >> $GITHUB_PATH
      -
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer,php-cs-fixer
          coverage: none
      -
        name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      -
        name: Cache composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ secrets.CACHE_VERSION }}-
      -
        name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ secrets.CACHE_VERSION }}-
      -
        name: Install packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y fping python3-pip python3-setuptools snmp sqlite3
      -
        name: Pip install
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade --user pylint python-memcached mysqlclient
      -
        name: Composer validate
        run: |
          composer validate
      -
        name: Init env
        run: |
          cat > .env <<EOL
          APP_KEY=base64:vHI+YHgkyCDad31iPEErGSNEOWO21wNzV+zyENKQv04=
          APP_URL=http://127.0.0.1:8000
          APP_ENV=testing
          DB_DRIVER=mysql
          DB_HOST=127.0.0.1
          DB_PORT=${{ job.services.database.ports[3306] }}
          DB_DATABASE=librenms_phpunit_78hunjuybybh
          DB_USERNAME=librenms
          DB_PASSWORD=librenms
          DB_TEST_DRIVER=mysql
          DB_TEST_HOST=127.0.0.1
          DB_TEST_PORT=${{ job.services.database.ports[3306] }}
          DB_TEST_DATABASE=librenms_phpunit_78hunjuybybh
          DB_TEST_USERNAME=librenms
          DB_TEST_PASSWORD=librenms
          EOL
      -
        name: Composer install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
      -

        name: Snmpsim setup
        run: |
          php lnms dev:simulate --setup-venv
      -
        name: Copy seeded config
        run: cp "${GITHUB_WORKSPACE}/tests/testing_config.yaml" "${GITHUB_WORKSPACE}/database/seeders/config/"
      -
        name: Ensure MySQL is up
        env:
          PORT: ${{ job.services.database.ports[3306] }}
        run: |
          mysqladmin -h"127.0.0.1" -P"$PORT" --user=librenms --password=librenms ping --wait=5
      -
        name: Set MySQL authentication plugin
        if: matrix.database == 'mysql:8.0'
        env:
          PORT: ${{ job.services.database.ports[3306] }}
        run: |
          mysql -h"127.0.0.1" -P"$PORT" --user=root -e "ALTER USER 'librenms'@'%' IDENTIFIED WITH mysql_native_password BY 'librenms'"
      -
        name: Set MySQL collate
        env:
          PORT: ${{ job.services.database.ports[3306] }}
        run: |
          mysql -h"127.0.0.1" -P"$PORT" --user=librenms --password=librenms -e 'ALTER DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
      -
        name: Setup SQLite
        run: sqlite3 database/testing.sqlite ""

      -
        name: Migrate Database
        run: php artisan migrate

      -
        name: Start SNMPSIM
        if: matrix.skip-unit-check != '1'
        run: |
          .python_venvs/snmpsim/bin/snmpsim-command-responder-lite --data-dir=tests/snmpsim --agent-udpv4-endpoint=127.1.6.2:1162 --log-level=error --logging-method=file:/tmp/snmpsimd.log &

      -
        name: lnms dev:check ci (OS)
        if: matrix.skip-unit-check != '1'
        run: |
          php lnms dev:check ci --os ${{ matrix.shard }}
        env:
          SKIP_WEB_CHECK: 1

      -
        name: lnms dev:check ci
        if: matrix.skip-web-check != '1'
        run: |
          php lnms dev:check ci --full --exclude-phpunit-group=os,mibs

      -
        name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      -
        name: Dump snmp logs
        if: failure() && matrix.skip-unit-check != '1'
        run: |
          cat /tmp/snmpsimd.log || true

      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
