name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - name: deps
      run: |
        sudo apt-get install -y snmp fping python3-pip python3-setuptools
        pip3 install --user snmpsim
        pip install --user mysql-python pylint        
    - name: setup mysql db
      run: | 
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} --user=root --password=root -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp tests/config/config.test.php config.php
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        APP_ENV: testing
      run: |
        set -e
        export FILES=$(git diff --diff-filter=d --name-only master | tr '\n' ' '|sed 's/,*$//g')
        php scripts/pre-commit.php -q -l
        php scripts/pre-commit.php -q -s
        php scripts/pre-commit.php -u --db --snmpsim --fail-fast
        test -z "$BROWSER_TEST" || php artisan dusk
        bash -n daily.sh
        pylint -E poller-wrapper.py discovery-wrapper.py
        bash scripts/deploy-docs.sh
        set +e
