name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      PATH: /home/runner/.local/bin/:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/runner/.dotnet/tools:/home/runner/.config/composer/vendor/bin
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    
    steps:
    - name: Verify MariaDB connection
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          echo "mysql not up yet"
          sleep 1
        done     
    - name: setup mysql db
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: | 
        mysql -h"127.0.0.1" -P"$PORT" --user=root --password=root -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
    - name: deps
      run: |
        sudo apt-get install -y snmp fping python3-pip python3-setuptools
        pip3 install --user snmpsim
        pip install --user wheel  
        pip install --user mysql-python pylint            
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp tests/config/config.test.php config.php
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: fetch master branch
      run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin master

    - name: Execute tests
      env:
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        php scripts/pre-commit.php -l     
    - name: Execute tests
      env:
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        export FILES=composer.lock
        php scripts/pre-commit.php -s
    - name: Execute tests
      env:
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        php scripts/pre-commit.php -u --db --snmpsim --fail-fast
    - name: Execute tests
      env:
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        test -z "$BROWSER_TEST" || php artisan dusk           
    - name: Execute tests
      env:
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        bash -n daily.sh

    - name: Execute tests
      env:
        APP_ENV: testing
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        pylint -E poller-wrapper.py discovery-wrapper.py
        

    - name: Execute tests
      env:
        APP_ENV: testing
        DB_TEST_PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        bash scripts/deploy-docs.sh        
